[ping_servers]
; список серверов дл€ пинговани€
s1 = srv-sitrol
s2 = srv-dev
s3 = srv-dv
s4 = srv-atdp
s5 = srv-dv-atdp
s6 = srv-dv-pg
s7 = srv-mail
s8 = dc-3
s9 = sh-407-9
s10 = sh-407-4
s11 = srv-sitrol2
s12 = srv-sitrol3

[email]
; хост и порт SMTP-сервера
host = srv-mail
port = 465
; тема письма
subject = ”ведомление о доступности серверов
; адрес электронной почты отправител€ (т.е. "от кого")
from = ping_srvs@mail.local
; адрес электронной почты получател€ (т.е. "кому")
to = everybody@mail.local
; признак "SSL/TLS" дл€ SMTP-сервера
tls = yes
; логин дл€ SMTP-сервера с аутентификацией (не заполн€ть, если сервер без аутентификации)
user = ping_srvs
; логин дл€ SMTP-сервера с аутентификацией (не заполн€ть, если сервер без аутентификации)
password = PaSsWord404
